# Generated by Django 4.2.11 on 2024-03-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='tc_n',
            new_name='trin',
        ),
    ]
